### ISSUE TITLE
代码高亮后没有行号

### ISSUE THREAD

**Issue by Codeapes666** [g1eny0ung/hugo-theme-dream#105]
你好，很喜欢这个主题。我想咨询下，代码高亮后没有显示行号和复制按钮，目前是不支持吗。

**Comment by g1eny0ung** [comment]
参考这个来配置语法高亮: [https://gohugo.io/getting-started/configuration-markup#highlight](https://gohugo.io/getting-started/configuration-markup#highlight)，复制没有支持。

开启行号：

```toml
[markup]
  [markup.highlight]
    lineNos = true
```
