### ISSUE TITLE
Add highlightjs for code syntax; possibly pick a light and dark theme as well

### ISSUE THREAD

**Issue by KoderKow** [g1eny0ung/hugo-theme-dream#141]
Love the theme! I have a few posts that involve some code, I find syntax highlighting makes the code more engaging and easier to read. I have found out that Hugo can easily implement [highlightjs](https://highlightjs.org/). I have been able to get any theme I want working with your theme, but, I cannot figure out how to switch between two different highlightjs themes when toggling the theme. In [Params](https://github.com/KoderKow/koderkow/blob/master/config.toml) I currently have:

```toml
[params]
  highlightjsVersion = "10.1.2"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"
  background = "#252323"
``` 

I would like:

```toml
highlightjsThemeDark = "rainbow"
highlightjsThemeLight = "github"
```

Example for code highlighting in my post: https://koderkow.rbind.io/post/introduction-to-neural-networks/

I have tried setting up a light/dark variable, however, I have no experience with Hugo code so I have had a hard time trying to get this to work with your theme. [Here](https://github.com/KoderKow/koderkow/tree/master/themes/hugo-theme-dream/layouts/partials) is a link to my current work on the partials. I got the highlight js Hugo code from [here](https://github.com/yihui/hugo-lithium/tree/master/layouts/partials).

Can I get some help implementing this?
