### ISSUE TITLE
Missing language toggle?

### ISSUE THREAD

**Issue by Sp-cy** [g1eny0ung/hugo-theme-dream#160]
I'm not sure i understand how multilingual support should work in Hugo pages. 
I already set my two languajes in site params like this: 

```
[languages]
  [languages.es]
    languageCode = "es"
    weight = 1

  [languages.en]
    languageCode = "en-us"
    weight = 2
```
 
Then I have tried to duplicate one of my posts in content and adding "en" to the file name like it says in Hugo docs but I can't get to the translated page in any way. I don't get an error and the page isn't duplicated, it's just invisible. My content files look something like this now:

> taco-taco-taco.md

> taco-taco-taco.en.md

Shouldn't the theme have a switch or menu somewhere to select the prefered languaje?

**Comment by g1eny0ung** [comment]
I test in my blog with:

```toml
baseURL = "https://g1eny0ung.site"
defaultContentLanguage = "zh"
theme = "dream"

[languages]
  [languages.zh]
    languageCode = "zh-Hans"
    title = "g1eny0ung 的博客"
  [languages.en]
    languageCode = "en"
    title = "g1eny0ung's blog"

    [languages.en.params]
      headerTitle = "g1eny0ung's blog"
```

Then I duplicate a post with `.en.md` affix to test, seems everything works fine. For local development env, type http://localhost:1313/en.

Maybe you forgot to set the `defaultContentLanguage` I guess?
