### ISSUE TITLE
Can't seem to able change post image size

### ISSUE THREAD

**Issue by kdpuvvadi** [g1eny0ung/hugo-theme-dream#175]

**Comment by g1eny0ung** [comment]
Yes. The current layout has only 4 columns on a large screen. I think what you might need is more column layout, like 5 columns?

Or the single specified post can be enlarged.

**Comment by kdpuvvadi** [comment]
No, not columns. Image of post in the Post page like posts/something

**Comment by g1eny0ung** [comment]
Know about it. I'm just making it center and cover the whole space. To adjust its width, you must ensure it has enough size, then override the CSS properties, fill the below content to a CSS file and import it from `customCSS` param:

```css
.dream-single .cover .cover-img {
  background-position: unset;
  background-size: unset;
}
```

These will reset the theme predefined. You can then continue to add the effects you want.
