### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by Godnyx** [g1eny0ung/hugo-theme-dream#184]
I have set "enableSearch" to 'true' and it's showing up and I can type the info but I won't get results. Is there a case I'm missing something that has to do with JS? I'm a JS noob!

**Comment by g1eny0ung** [comment]
Are you putting the below content in your `config.toml`?

```toml
[outputs]
  home = ["HTML", "RSS", "JSON"]
```

The search function relies on a JSON output file that includes all indexes of your posts.
