### ISSUE TITLE
How do i change the font?

### ISSUE THREAD

**Issue by 33nano** [g1eny0ung/hugo-theme-dream#189]
I'm loving the theme, but the font is kinda hard to read. How would i change the font to something like Libre Baskerville?

**Comment by g1eny0ung** [comment]
For now, you can use https://g1eny0ung.site/hugo-theme-dream/#/params-configurations?id=customcss-quotcsscustomcssquot to replace the default fonts.

For example, overwrite the body's `font-family` by [Google Fonts](https://fonts.google.com/):

```css
/* custom.css */
@import url('https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&display=swap');

body {
  font-family: 'Libre Baskerville', serif !important;
}
```

And to be noted that, it's better to build an own custom `semantic.min.css` to finish this thing. Here is the ref: https://semantic-ui.com/usage/theming.html. I will provide a small tutorial and some params to complete this work later.
