### ISSUE TITLE
拉取了今天最新的版本，切换灯光为暗色时，icon不显示

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#198]
拉取了今天最新的版本，切换灯光为暗色时，顶部菜单栏icon、底部页脚部分一片白色，内容无法展示

**Comment by kuole-o** [comment]
可以这里查看问题https://guole.fun/ 找了半天，没发现原因 。。

**Comment by g1eny0ung** [comment]
因为背景是白色的。

**Comment by kuole-o** [comment]
> 因为背景是白色的。

我记得 第一次部署上去时，好像是正常的，就前两天。而且 你的blog一样配色，那个功能是正常的啊  求指点 😭😭😭

又是强迫症，就老想点那个。

这个功能，不是通过css去改变样式达到的效果吗 我应该怎么使他正常呢😳

**Comment by g1eny0ung** [comment]
可以用自定义 CSS 来解决这个问题，这里有两种方法。

## 准备工作

首先在配置文件里指定一下自定义文件：

```toml
[params]
  [params.advanced]
    customCSS = ["css/custom.css"]
```

然后创建 `static/css/custom.css`。

## 方法1

比如我在我的博客里添加了这样一段样式：

```css
body.dark .os-viewport {
  background-color: rgba(0, 0, 0, 0.6);
}
```

这段样式会在切换到暗色的时候给背景加上一个 60% 透明度的黑色浮层（可以调整成你觉得比较舒服的颜色），这样顶部的导航栏就可以被看到了。

## 方法2

强行固定导航栏的颜色：

```css
.os-content > .dream-menu > .item {
  color: inherit !important;
}
```
