### ISSUE TITLE
关于页面左上角icon

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#201]
是这样的，现在的“翻转”icon，个人觉得有“翻转”的感觉，但是不能体现“点击可查看个人更多信息”的意思，就想自己换一个。已经icon换上去了，但是点击的页面翻转效果 如何链接呢 求指导 😂😂
![image](https://user-images.githubusercontent.com/63436555/118440976-13da3680-b71b-11eb-9e17-69d96e60aab2.png)
![image](https://user-images.githubusercontent.com/63436555/118440978-150b6380-b71b-11eb-9ba8-78a54adcc802.png)

**Comment by kuole-o** [comment]
另外想问问，dream主题中引用的icon，是如何实现的？我如何查看 这个icon库支持了哪些？因为上次偶然引用 music 发现也能直接用

**Comment by g1eny0ung** [comment]
> 另外想问问，dream主题中引用的icon，是如何实现的？我如何查看 这个icon库支持了哪些？因为上次偶然引用 music 发现也能直接用

https://semantic-ui.com/.

同时，翻转效果需要 `.dream-flip-toggle` 这个 class，JS 代码会根据它来绑定触发翻转的函数到对应的元素上。

**Comment by kuole-o** [comment]
了解了 感谢~~

**Comment by kuole-o** [comment]
老哥，求指点  用你说的方法，加了个 .dream-flip-toggle 后，首页可以正常展示icon且点击有翻转效果了。但是md文章页，为什么不展示这个icon呢？

我也试了在 head.html 等文件中，重新加一遍，引用那个icon fonts的css，可是依然不展示。实在没法子了   请有空看到后，指点下

![image](https://user-images.githubusercontent.com/63436555/118592270-4bf37f00-b7d8-11eb-87c7-248c0c68cf6e.png)
![image](https://user-images.githubusercontent.com/63436555/118592329-5ca3f500-b7d8-11eb-91e5-a4d1baffd00e.png)

**Comment by kuole-o** [comment]
忽略上面。。我直接引用dream预设的那个icon库  问题解决了。。。

**Comment by g1eny0ung** [comment]
> 忽略上面。。我直接引用dream预设的那个icon库 问题解决了。。。

👌🏽

**Comment by RuikangSun** [comment]
> 
> 
> > 另外想问问，dream主题中引用的icon，是如何实现的？我如何查看 这个icon库支持了哪些？因为上次偶然引用 music 发现也能直接用
> 
> https://semantic-ui.com/.
> 
> 也可以用 https://icomoon.io/ 自定义，比如我就自定义了一个：[https://github.com/g1eny0ung/hugo-theme-dream/blob/master/static/css/icomoon.css。](https://github.com/g1eny0ung/hugo-theme-dream/blob/master/static/css/icomoon.css%E3%80%82)
> 
> 同时，翻转效果需要 `.dream-flip-toggle` 这个 class，JS 代码会根据它来绑定触发翻转的函数到对应的元素上。

作者您好，请教您dream主题下的图标是如何配置来源的？如果我想使用[IconPark](https://iconpark.oceanengine.com/home)或者[iconfont](https://www.iconfont.cn/)图标，应该在哪里配置？

顺便一提，您的主题已经被我部署到了生产环境（[生化环材网](https://shhc.tech/)）了。

谢谢！

**Comment by kuole-o** [comment]
> 作者你好，请教你梦想主题下的图标是如何配置来源的？如果我想使用[IconPark](https://iconpark.oceanengine.com/home)或者[iconfont](https://www.iconfont.cn/)图标，应该在哪里配置？
> 
> 丰一提，您的主题已经被我部署到了生产环境（[生化环材网](https://shhc.tech/)）了。
> 
> 谢谢！

dream左上角的icon，似乎只能使用 **https://semantic-ui.com/elements/icon.html#brands**这里的icon。在 nav.html 里修改或增加一个菜单栏按钮即可。最好复制主题里的nav.html到blog/layouts/partials/nav.html，然后自定义  
  
比如下面这里，第一个item是左上角第一个“翻转”按钮的icon，我觉得翻转后是个人信息，因此换成了```address card```，更换icon后，为了绑定原有的点击翻转效果，因此添加了一个```dream-flip-toggle```类。  
  
而自己新增一个菜单栏入口，同样很简单，找到一个喜欢的icon，设置对应url即可。
```html
  <div class="item">
    <div class="dream-flip-toggle" >
    <i class="large link bullseye icon address card" title="{{ i18n "flip" }}"></i>
  </div>
</div>

<!-- 这里是我自定义添加的，去往音乐小站的入口 -->
  <div class="item">
    <i class="large link music icon" title="{{ i18n "music" }}" onclick="window.location.href = 'https://music.guole.fun/'" target="_blank"></i>
  </div>
```

**Comment by RuikangSun** [comment]
> 
> 
> > 作者你好，请教你梦想主题下的图标是如何配置来源的？如果我想使用[IconPark](https://iconpark.oceanengine.com/home)或者[iconfont](https://www.iconfont.cn/)图标，应该在哪里配置？
> > 丰一提，您的主题已经被我部署到了生产环境（[生化环材网](https://shhc.tech/)）了。
> > 谢谢！
> 
> dream左上角的icon，似乎只能使用 **[https://semantic-ui.com/elements/icon.html#brands**这里的icon。在](https://semantic-ui.com/elements/icon.html#brands**%E8%BF%99%E9%87%8C%E7%9A%84icon%E3%80%82%E5%9C%A8) nav.html 里修改或增加一个菜单栏按钮即可。最好复制主题里的nav.html到blog/layouts/partials/nav.html，然后自定义
> 
> 比如下面这里，第一个item是左上角第一个“翻转”按钮的icon，我觉得翻转后是个人信息，因此换成了`address card`，更换icon后，为了绑定原有的点击翻转效果，因此添加了一个`dream-flip-toggle`类。
> 
> 而自己新增一个菜单栏入口，同样很简单，找到一个喜欢的icon，设置对应url即可。
> 
> ```
>   <div class="item">
>     <div class="dream-flip-toggle" >
>     <i class="large link bullseye icon address card" title="{{ i18n "flip" }}"></i>
>   </div>
> </div>
> 
> 
>   <div class="item">
>     <i class="large link music icon" title="{{ i18n "music" }}" onclick="window.location.href = 'https://music.guole.fun/'" target="_blank"></i>
>   </div>
> ```

十分感谢！

**Comment by kuole-o** [comment]
目前似乎只能在作者“联系方式”处，添加自定义图标。比如我使用了iconfont的bilibili图标。  
  
在自定义的css文件里，增加下面这样的内容：
```css
@font-face {
  font-family: 'icomoon';
  src: url('fonts/icomoon.eot?ts82yo');
  src: url('fonts/icomoon.eot?ts82yo#iefix') format('embedded-opentype'),
    url('fonts/icomoon.ttf?ts82yo') format('truetype'), url('fonts/icomoon.woff?ts82yo') format('woff'),
    url('fonts/icomoon.svg?ts82yo#icomoon') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}

[class^='icon-'],
[class*=' icon-'] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'icomoon' !important;
  speak: never;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.icon-mastodon:before {
  content: '\e900';
}


@font-face {
  font-family: "iconfont"; /* Project id 2552329 */
  src: url('//at.alicdn.com/t/font_2552329_8gaurozio15.woff2?t=1621307959530') format('woff2'),
       url('//at.alicdn.com/t/font_2552329_8gaurozio15.woff?t=1621307959530') format('woff'),
       url('//at.alicdn.com/t/font_2552329_8gaurozio15.ttf?t=1621307959530') format('truetype');
}

.iconfont {
  font-family: "iconfont" !important;
  font-size: 1.7em;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.iconfont icon-mingpian1{
  color:#373737;  /*可轻松改变图标颜色*/
  /* font-size:24px;  改变图标的大小*/
  }

.icon-qqyinle:before {
  content: "\e9b7";
}

.icon-QQMusic:before {
  content: "\e601";
}

.icon-mingpian:before {
  content: "\e62c";
}

.icon-mingpian1:before {
  content: "\e709";
}

.icon-bilibili:before {
  content: "\e652";
}

  .iconfont{cursor: pointer;} /*鼠标移动到button上显示一个小手，与dream其他icon样式一致*/

```
以上内容，你可以在你的iconfont项目中获取：
![image](https://user-images.githubusercontent.com/63436555/123725160-2f129700-d8c0-11eb-92e8-399958c880d8.png)
