### ISSUE TITLE
关于代码高亮

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#213]
我设置了一个网上的代码高亮方法，但是。。不生效。刷新页面时，能发现 一开始是正常显示出效果的，但等页面加载完成，代码字体又被白色覆盖了，导致效果又没了  
  
可以在这里，查看我说的问题。页面 刷新快一点，就能看到我描述的样子。很苦恼，不知道是咋回事儿，只能再发到这里了   老哥闲暇有空的时候，也请再帮忙看看吧  
https://guole.fun/chat/message/

**Comment by kuole-o** [comment]
配置文件里，这样写的，除此之外，也没有做什么了：

    [markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      noClasses = true
      style = "dracula"
      tabWidth = 4

**Comment by kuole-o** [comment]
去掉了自己改的内容，直接参考你的配置：
  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["clojure", "ocaml"]
  highlightjsTheme = "tomorrow"
  highlightjsThemeDark = "tomorrow-night"
还是不太行，同样的 页面刷新时前几秒有高亮效果，接着字体全白色了，看不清了

**Comment by kuole-o** [comment]
去掉了自己改的内容，直接参考你的配置：
```toml
highlightjs = true
highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
highlightjsExtraLanguages = ["clojure", "ocaml"]
highlightjsTheme = "tomorrow"
highlightjsThemeDark = "tomorrow-night"
```
还是不太行，同样的 页面刷新时前几秒有高亮效果，接着字体全白色了，看不清了
