### ISSUE TITLE
夜间模式适配了自己添加的插件，pc端不生效，移动端正常

### ISSUE THREAD

**Issue by kuole-o** [g1eny0ung/hugo-theme-dream#214]
老哥，这个问题自己真的搞不了，查了好久，还是搞不定。[出现问题的页面，点此查看](htttps://guole.fun/bb/ )  求指点  
  
我在自定义 css 文件里，加了一句，自己加的那个插件，移动端夜间模式下，能正常用了。  
```css
body.dark div.timenode .body{ background: #222 !important;}  
```
![image](https://user-images.githubusercontent.com/63436555/120457055-bc99be80-c3c8-11eb-8d99-296d87f17ef7.png)
  
奇怪的是，pc端，夜间模式 还是一片空白，看不清字。请指点
![image](https://user-images.githubusercontent.com/63436555/120457362-f7035b80-c3c8-11eb-9e87-dc514d2d5e49.png)

**Comment by g1eny0ung** [comment]
因为你设置了 [`media query`](http://developer.mozilla.org/en-US/docs/Web/CSS/@media)。

**Comment by kuole-o** [comment]
老哥 能不能展开讲讲，我应该咋改呢   
```css
body.dark div.timenode .body{ background: #222 !important;}  
```
这句，咋写能pc 移动端夜间模式下，都正常呢

**Comment by kuole-o** [comment]
我添加了个上下文链接，使用 ```body.dark``` 设置夜间模式颜色，也是移动端正常，pc不生效   这个没涉及你说的 media 什么的  
```html
<!--  上下文链接  --> 
<div class="pagination" style="text-align: center; margin-top: 0.5em; margin-bottom: 0.2em; padding: 0.5em; ">
  {{ if .Next }}
    <span class="button previous" >
      <a href="{{ .Next.Permalink }}">
        <span class="button__icon" style="color:seagreen !important; font-size:1em;" ><<</span>
        <span class="button__text" style="color:seagreen !important; font-size:0.8em;">{{ .Next.Title }}&emsp;</span>
      </a>
    </span>
  {{ end }}

  {{ if .Prev }}
    <span class="button next">
      <a href="{{ .Prev.Permalink }}">
        <span class="button__text" style="color:seagreen !important; font-size:0.8em; ">&emsp;{{ .Prev.Title }}</span>
        <span class="button__icon" style="color:seagreen !important; font-size:1em;">>></span>
      </a>
    </span>
  {{ end }}
</div>
```
ccs样式为：  
```css
body.dark span.button.previous { color:darkseagreen !important; background-color: rgba(53, 53, 53, 0.973) !important;}
body.dark span.button.next { color:darkseagreen !important; background-color: rgba(53, 53, 53, 0.973) !important;}
```
