### ISSUE TITLE
[Bug]: i18n for about

### ISSUE THREAD

**Issue by lskbr** [g1eny0ung/hugo-theme-dream#326]
### Version

master

### What browsers are you seeing the problem on?

Chrome, Firefox

### Describe the bug

Internationalization works very well in the theme, except for the About option.
In huho.toml
```toml
[languages]
  [languages.fr]
    contentDir = 'content/fr'
    disabled = false
    languageCode = 'fr-FR'
    languageDirection = 'ltr'
    languageName = 'French'
    title = 'InovaMakers'
    weight = 1
    [languages.fr.params]
      subtitle = 'Electronique'
      about = "À propos"
      motto = "Curiosité & Innovation"
  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Brazilian Portuguese'
    title = 'InovaMakers'
    weight = 2
    [languages.pt.params]
      subtitle = 'Electrônica'
      about = "Sobre"
      motto = "Curiosidade & Inovação"
```
All other i18n are working, except for about.

### To Reproduce

Visit https://inovamakers.com/en/
The about option should be shown.

Go to https://inovamakers.com/pt/
The Sobre should be displayed instead of About.

Go to https://inovamakers.com/fr/
The "À propos" should be displayed, instead About is displayed.
